config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }
  devise_for :user,skip:[:passwords],controllers:{
    registrations:'public/registrations',
    sessions:'public/sessions'
  }
  
  namespace :admin do
    root 'posts#index'
    get 'top'=>'homes#top'
    resources :posts,only:[:index,:show,:destroy]
    resources :users do
      member do 
        patch :withdraw
      end 
    end
  end  
  
  
  
  
  #ユーザー側のルーティング
  get 'homes/about'
  root to:'homes#top'
  
  devise_scope :user do
    post 'guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'user_guest_sign_in'
  end
  resources :users,only:[:index,:show,:edit,:update] do
    member do
      get :follows,:followers
    end 
    resource :relationships,only:[:create,:destroy]
  end   
  resources :posts do
    resources :post_comments,only:[:create,:destroy]
    resource :favorite,only:[:create,:destroy]
  end   
  get 'search'=>'searches#search'
  
  resources :events
  get 'favorites',to:'favorites#index',as:'user_favorites'
  #user退会処理
  get 'user/check'=>'users#check'
  patch 'user/withdraw'=>'users#withdraw'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end   

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image    
  validates :name,presence: true
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  # フォロー機能
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  has_many :events, dependent: :destroy
  
  def follow(user_id)
    followers.create(followed_id: user_id)
  end 
  
  def unfollow(user_id)
    followers.find_by(followed_id: user_id).destroy
  end 
  
  def following?(user)
    following_users.include?(user)
  end

  # ユーザーステータス
  def active_status
    is_active ? "有効" : "退会済み"
  end

  # 退会済みアカウントの処理
  def active_for_authentication?
    super && (is_active == true)
  end

  # プロフィール写真
  def get_profile_image(width, height)
    if profile_image.attached?
      profile_image.variant(resize_to_fill: [width, height]).processed
    else
      'no_profile.jpg'
    end 
  end
  
  # 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

  # ゲストログイン機能
  def self.guest
    email = "guest_#{SecureRandom.uuid}@example.com"
    find_or_create_by!(email: email) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
  #いいねされているか確認
  def favorited?(post)
    favorites.exists?(post_id: post.id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :set_user, only: [:show,:withdraw]
    def index
        @users = User.all
    end 
    
    def show
        @following_users = @user.following_users
        @follower_users = @user.follower_users
    end 
    def withdraw
        @user = User.find(params[:id])
        if @user.update(is_active: false)
          flash[:notice] = "退会処理を実行いたしました"
          redirect_to admin_users_path
        else
          flash[:alert] = "退会処理に失敗しました"
          redirect_to admin_user_path(@user)
        end
    end
    
   
private 
    def set_user
        @user = User.find(params[:id])
    end
    def user_params
        params.require(:user).permit(:name,:email,:is_active)
    end     
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def index
    @post = Post.new 
    @user = current_user
    @users = User.where(is_active: true).page(params[:page]).per(8)
  end 

  def show
    @post = Post.new
    @user = User.find(params[:id])
  end     

  def edit 
    @user = User.find(params[:id])
  end 

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'プロフィールが更新されました。'
    else
      render :edit, alert: 'プロフィールの更新に失敗しました。'
    end
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.following_users.page(params[:page]).per(8)
  end 

  def followers
    @user = User.find(params[:id])
    @followers = @user.follower_users.page(params[:page]).per(8)
  end 

  def check
  end 

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_active: false)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end     

private 
  def is_matching_login_user
    unless user_signed_in? && current_user.id == params[:id].to_i
      flash[:alert] = "ログインしてください"
      redirect_to root_path
    end 
  end     

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end     
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<% if user_signed_in?%>
<div class="card mb-4">
  <div class="card-header bg-primary text-white">
    <h4 class="text-center">ユーザー情報</h4>
  </div>
  <div class="card-body text-center">
    <% if user %>
      <% profile_image_path = user.get_profile_image(100, 100) rescue 'no_profile.jpg' %>
      <% if profile_image_path != 'no_profile.jpg' %>
        <%= image_tag profile_image_path, class: 'img-fluid rounded-circle mb-3', style: 'width: 100px; height: 100px;' %>
      <% else %>
        <%= image_tag 'no_profile.jpg', class: 'img-fluid rounded-circle mb-3', style: 'width: 100px; height: 100px;' %>
      <% end %>
      <h5>ユーザー名: <%= link_to user.name,user_path(user) %></h5>
      <% if current_user&.id == user.id %>
        <%= link_to raw('<i class="fa-solid fa-gear"></i> プロフィールを編集'), edit_user_path(user.id), class: "btn btn-outline-primary mt-3" %>
      <% end %>
    <% else %>
      <%= image_tag 'no_profile.jpg', class: 'img-fluid rounded-circle mb-3', style: 'width: 100px; height: 100px;' %>
      <h5>ユーザー名: 不明</h5>
    <% end %>

    <!-- フォロー数とフォロワー数の表示 -->
    <div class="d-flex justify-content-center mt-3">
      <%= link_to follows_user_path(user), class: 'text-decoration-none me-3 follow-link' do %>
        <h6><%= user.followers.count %>フォロー中</h6>
      <% end %>
      <%= link_to followers_user_path(user), class: 'text-decoration-none follow-link' do %>
        <h6><%= user.followeds.count %>フォロワー</h6>
      <% end %>
    </div>

    <!-- フォローボタン -->
    <% if current_user != user %>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger mt-3" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success mt-3" %>
      <% end %>
    <% end %>
  </div>
</div>
<% end %>

app/views/users/check.html.erb
<div class="container text-center">
  <h1>本当に退会しますか？</h1>
  <p>
    退会すると、会員登録情報や<br>
    これまでの購入履歴が閲覧できなくなります。<br>
    退会する場合は、「退会する」をクリックしてください。
  </p>
  <div class="d-flex justify-content-center mt-4">
    <%= link_to "退会しない", user_path(current_user), class: "btn btn-primary me-2" %>
    <%= link_to "退会する", user_withdraw_path, method: :patch, class: "btn btn-danger ms-2", data: { confirm: "本当に退会しますか？" } %>
  </div>
</div>

app/views/users/edit.html.erb
<h2 class="text-center">プロフィール編集</h2>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <!-- エラーメッセージ表示部分 -->
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <h4>入力に問題があります:</h4>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with model: @user, local: true, html: { class: 'form' } do |f| %>
        <div class="mb-3">
          <%= f.label :name, "名前" %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :profile_image, "プロフィール画像" %>
          <%= f.file_field :profile_image, accept: "image/*", class: 'form-control' %>
        </div>
        <div class="d-grid mt-4">
          <%= f.submit '更新', class: 'btn btn-primary btn-block' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center mt-4">
    <div class="col-md-6 text-center">
      <%= link_to "退会フォーム", user_check_path, class: "btn btn-danger btn-sm" %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2><%= @user.name%>さんのフォロワー一覧</h2>
<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Follows</th>
      <th>Followers</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% if @followers.present? %>
      <% @followers.each do |follower| %> 
        <tr>
          <td>
            <%= link_to user_path(follower) do %>
              <%= image_tag follower.get_profile_image(50, 50), class: 'rounded-circle' %>
            <% end %>
          </td>
          <td><%= link_to follower.name,user_path(follower) %></td>
          <td>
            <%= link_to follows_user_path(follower), class: 'text-decoration-none' do %>
              <h6><%= follower.following_users.count %> フォロー</h6>
            <% end %>
          </td>
          <td>
            <%= link_to followers_user_path(follower), class: 'text-decoration-none' do %>
              <h6><%= follower.follower_users.count %> フォロワー</h6>
            <% end %>
          </td>
          <td>
            <% if current_user != follower %>
              <% if current_user.following?(follower) %>
                <%= link_to "フォローを外す", user_relationships_path(follower.id), method: :delete, class: "btn btn-danger btn-sm" %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(follower.id), method: :post, class: "btn btn-success btn-sm" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="5" class="text-center">フォロワーがいません</td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination-container">
  <%= paginate @followers %>
</div>

app/views/users/follows.html.erb
<h2><%= @user.name%>さんのフォロー一覧</h2>
<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Follows</th>
      <th>Followers</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% if @users.present? %>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user) do %>
              <%= image_tag user.get_profile_image(50, 50), class: 'rounded-circle' %>
            <% end %>
          </td>
          <td><%= link_to user.name,user_path(user) %></td>
          <td>
            <%= link_to follows_user_path(user), class: 'text-decoration-none' do %>
              <h6><%= user.following_users.count %> フォロー</h6>
            <% end %>
          </td>
          <td>
            <%= link_to followers_user_path(user), class: 'text-decoration-none' do %>
              <h6><%= user.follower_users.count %> フォロワー</h6>
            <% end %>
          </td>
          <td>
            <% if current_user != user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger btn-sm" %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success btn-sm" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="5" class="text-center">フォローしているユーザーがいません</td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="pagination-container">
  <%= paginate @users %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <!-- ユーザー情報と投稿フォーム -->
    <div class="col-md-4">
      <!-- ユーザー情報 -->
      <div class="mb-4">
        <%= render "users/profile", user: @user %>
      </div>
      <!-- 投稿フォーム -->
      <div class="mb-4">
        <%= render "posts/new" %>
      </div>
    </div>

    <!-- ユーザー一覧 -->
    <div class="col-md-8">
      <h1 class="text-center my-4">ユーザー一覧</h1>
      <div class="row">
        <% @users.each do |user| %>
          <div class="col-md-6 mb-4">
            <div class="card">
              <div class="card-body text-center">
                <% profile_image = user.get_profile_image(100, 100) %> 
                <% if profile_image.is_a?(ActiveStorage::VariantWithRecord) %>
                  <%= link_to user_path(user) do %>
                    <%= image_tag profile_image, class: 'img-fluid rounded-circle mb-3', style: 'width: 100px; height: 100px;' %>
                  <% end %>
                <% else %>
                  <%= link_to user_path(user) do %>
                    <%= image_tag 'no_profile.jpg', class: 'img-fluid rounded-circle mb-3', style: 'width: 100px; height: 100px;' %>
                  <% end %>
                <% end %>
                <h5 class="card-title">
                  <%= link_to user.name, user_path(user), class: 'text-dark' %>
                </h5>
                <div class="d-flex justify-content-center mt-3">
                  <%= link_to follows_user_path(user), class: 'text-decoration-none me-3 follow-link' do %>
                    <h6><%= user.followers.count %>フォロー中</h6>
                  <% end %>
                  <%= link_to followers_user_path(user), class: 'text-decoration-none follow-link' do %>
                    <h6><%= user.followeds.count %>フォロワー</h6>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="pagination-container">
  <%= paginate @users %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <!-- ユーザー情報と投稿フォーム -->
    <div class="col-md-4">
      <!-- ユーザー情報 -->
      <div class="mb-4">
        <%= render "users/profile", user: @user %>
      </div>
      <!-- 投稿フォーム -->
      <div class="mb-4">
        <%= render "posts/new" %>
      </div>
    </div>

     <!-- 過去の投稿 -->
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h3>過去の投稿</h3>
          <% if @user.posts.any? %>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>タイトル</th>
                  <th>内容</th>
                  <th>コメント数</th>
                  <th>投稿日</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
                <% @user.posts.each do |post| %>
                  <tr>
                    <td><%= link_to post.title, post_path(post) %></td>
                    <td><%= post.content %></td>
                    <td><%= link_to "#{post.post_comments.count}コメント",post_path(post.id)%></td>
                    <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
                    <td>
                      <% if @user.id == current_user.id %>
                        <%= link_to "編集", edit_post_path(post), class: "btn btn-info btn-sm" %>
                        <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "本当に削除しますか?" }, class: "btn btn-danger btn-sm" %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p>過去の投稿はありません</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>