config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }
  devise_for :user,skip:[:passwords],controllers:{
    registrations:'public/registrations',
    sessions:'public/sessions'
  }
  
  namespace :admin do
    root 'posts#index'
    get 'top'=>'homes#top'
    resources :posts,only:[:index,:show,:destroy]
    resources :users do
      member do 
        patch :withdraw
      end 
    end
  end  
  
  
  
  
  #ユーザー側のルーティング
  get 'homes/about'
  root to:'homes#top'
  
  devise_scope :user do
    post 'guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'user_guest_sign_in'
  end
  resources :users,only:[:index,:show,:edit,:update] do
    member do
      get :follows,:followers
    end 
    resource :relationships,only:[:create,:destroy]
  end   
  resources :posts do
    resources :post_comments,only:[:create,:destroy]
    resource :favorite,only:[:create,:destroy]
  end   
  get 'search'=>'searches#search'
  
  resources :events
  get 'favorites',to:'favorites#index',as:'user_favorites'
  #user退会処理
  get 'user/check'=>'users#check'
  patch 'user/withdraw'=>'users#withdraw'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end   

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_user!
    
    def search
        @range = params[:range]
        if @range == "User"
            @users = User.looks(params[:search],params[:word]).page(params[:page]).per(10)
        else
            @posts = Post.looks(params[:search],params[:word]).page(params[:page]).per(10)
        end     
    end    
    
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form d-flex justify-content-end">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Post']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<h2>検索結果</h2>

<div class="table-responsive">
  <table class="table table-hover table-bordered">
    <!-- 検索対象モデルが User の時 -->
    <% if @range == "User" %>
      <thead>
        <tr>
          <th scope="col">プロフィール画像</th>
          <th scope="col">名前</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td class="text-center">
              <% if user.profile_image.attached? %>
                <%= image_tag user.profile_image.variant(resize_to_fill: [100, 100]).processed, class: "img-thumbnail" %>
              <% else %>
                <%= image_tag user.get_profile_image(100, 100), class: "img-thumbnail" %> <!-- ここで引数を指定 -->
              <% end %>
            </td>
            <td>
              <%= link_to user.name, user_path(user), class: "text-decoration-none" %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="2">
            <div class="pagination-container text-center">
              <%= paginate @users %>
            </div>
          </td>
        </tr>
      </tfoot>
    <% else %>
      <!-- 検索対象モデルが Post の時 -->
      <thead>
        <tr>
          <th scope="col">タイトル</th>
          <th scope="col">内容</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td>
              <%= link_to post.title, post_path(post), class: "text-decoration-none" %>
            </td>
            <td><%= truncate(post.content, length: 100) %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="2">
            <div class="pagination-container text-center">
              <%= paginate @posts %>
            </div>
          </td>
        </tr>
      </tfoot>
    <% end %>
  </table>
</div>