config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }
  devise_for :user,skip:[:passwords],controllers:{
    registrations:'public/registrations',
    sessions:'public/sessions'
  }
  
  namespace :admin do
    root 'posts#index'
    get 'top'=>'homes#top'
    resources :posts,only:[:index,:show,:destroy]
    resources :users do
      member do 
        patch :withdraw
      end 
    end
  end  
  
  
  
  
  #ユーザー側のルーティング
  get 'homes/about'
  root to:'homes#top'
  
  devise_scope :user do
    post 'guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'user_guest_sign_in'
  end
  resources :users,only:[:index,:show,:edit,:update] do
    member do
      get :follows,:followers
    end 
    resource :relationships,only:[:create,:destroy]
  end   
  resources :posts do
    resources :post_comments,only:[:create,:destroy]
    resource :favorite,only:[:create,:destroy]
  end   
  get 'search'=>'searches#search'
  
  resources :events
  get 'favorites',to:'favorites#index',as:'user_favorites'
  #user退会処理
  get 'user/check'=>'users#check'
  patch 'user/withdraw'=>'users#withdraw'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end   

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <i class="fa-solid fa-book"><a class="navbar-brand" href="top">MyStyleDiary</a></i>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "ユーザー一覧",admin_users_path,class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧",admin_posts_path,class:"nav-link"%>
            </li>
                <% if admin_signed_in? %>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
                <% else %>
                <li><%= link_to "ログイン",new_user_session_path,class:"dropdown-item"%></li>
                <li><%= link_to "新規登録",new_user_registration_path,class:"dropdown-item"%></li>
                <% end %> 
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/_before_signin_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="/"><i class="fa-solid fa-book"></i> MyStyleDiary</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "他のユーザー", users_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "投稿一覧", posts_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "MyStyleDiaryとは", homes_about_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ユーザーページ
          </a>
          <ul class="dropdown-menu dropdown-menu-dark">
            <li><%= link_to "ログイン", new_user_session_path, class: "dropdown-item" %></li>
            <li><%= link_to "新規登録", new_user_registration_path, class: "dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_user_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="/"><i class="fa-solid fa-book"></i> MyStyleDiary</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "他のユーザー", users_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "投稿一覧", posts_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "カレンダー", events_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ユーザーページ
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to "マイページ", user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to "いいねした投稿",user_favorites_path,class:"dropdown-item"%></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
            <% else %>
              <li><%= link_to "ログイン", new_user_session_path, class: "dropdown-item" %></li>
              <li><%= link_to "新規登録", new_user_registration_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStyleDiary</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/5bd3e9a1d7.js" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', async: true %>
</head>
<body>
  <header>
    <% if user_signed_in? %>
      <%= render 'layouts/user_header' %>
    <% elsif admin_signed_in? %>
      <%= render 'layouts/admin_header' %>
    <% else %>
      <%= render 'layouts/before_signin_header' %>
    <% end %>
  </header>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= render 'searches/search' %>
  <%= yield %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>